[package]
name = "dos-client"
version = "0.1.0"
edition = "2021"

[dependencies]
dos-shared = { path = "../shared" }

bevy = { version = "0.7.0"}
bevy_egui = "0.14.0"
iyes_loopless = "0.6.1"
bincode = "1.3.3"