[package]
name = "dos-server"
version = "0.1.0"
edition = "2021"

[dependencies]
dos-shared = { path = "../shared" }

bevy = { version = "0.7.0"}
iyes_loopless = "0.6.1"
bincode = "1.3.3"
futures-lite = "1.12.0"