[package]
name = "dos-server"
version = "0.1.0"
edition = "2021"

[dependencies]
dos-shared = { path = "../shared" }

bevy = "0.8.0"
bevy_renet = "0.0.5"
iyes_loopless = "0.7.0"
bincode = "1.3.3"
futures-lite = "1.12.0"